version: '3.8'

services:
  postgres-db:
    image: postgres:14-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=agence_voitures
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - agence-network

  agence-voiture-app:
    build: .
    container_name: agence-voiture-app
    depends_on:
      - postgres-db
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/agence_voitures
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    volumes:
      - ./src/main/resources/static/img:/app/static/img
    networks:
      - agence-network
    restart: on-failure

networks:
  agence-network:
    driver: bridge

volumes:
  postgres-data:
